export const gray = '#dfdfdf'
export const darkGray = '#aaa'
export const textGray = '#666'
export const white = '#fff'
export const red = '#c30000'
export const green = 'darkgreen'
export const black = '#111'
